backend:
  name: github
  repo: CloCreative/CloCreative-clocreative.github.io
  branch: main
  auth_type: implicit

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/homepage.md"
        label: "Page d'accueil"
        name: "homepage"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
