backend:
  name: auth0
  domain: TON_DOMAINE_AUTH0
  client_id: TON_CLIENT_ID


media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Page d'accueil"
        name: "homepage"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
